### PR TITLE
Add signer attachments functionality

### PR DESCRIPTION
**Pull request by orlandobcrra**

### CODE REVIEW

**Comment by orlandobcrra** [comment]
hi @alexmac05 @jyoung488 
please If you could check this PR to allow attachments parameter, fixing issue #44 .
thanks.

**Comment by orlandobcrra** [comment]
hi @alexmac05 @jyoung488
please If you could check this PR to allow attachments parameter, fixing issue #44 .
thanks.

**Comment by oconnor-sn** [comment]
Housekeeping submitted and updated for this PR.

Please close off this PR.

**Comment by jtreminio-dropbox** [comment]
Please use the new OpenAPI SDK: https://pypi.org/project/dropbox-sign/

**Pull request closed without merging**
