### PR TITLE
Added page size parameter 

### PR DESCRIPTION
**Pull request by breigle**
Added page size parameter and updated doc string to method get_signature_request_list.

### CODE REVIEW

**Comment by alexmac05** [comment]
Hi breigle,

I will be looking at this pull request next week and either merge it or give feedback. Thank you so much for taking the time.

**Comment by alexmac05** [comment]
Hi Breigle,

This is on our short term todo list. This will be merged soon. Sorry for the delay

**Comment by breigle** [comment]
@alexmac05 merge time?

**Comment by alexmac05** [comment]
@breigle Yes. Sorry about the delay.

**Comment by alexmac05** [comment]
Hi Brian, 

There are a few issues with this pull request. I'll write it up in detail but it isn't a quick merge. I do apologize for the delay checking this.

**Review by BHSPitMonkey — APPROVED** [review]
LGTM :+1:  

Had some initial concerns about breaking existing usage of `ux_version` as a positional argument, but upon closer inspection it turns out that parameter shouldn't even be here and doesn't work. We'll remove it in a future commit.

**Comment by souldeux** [comment]
There are seven comments on this PR. Three of those seven contain an apology for the "delay" in processing this PR. This PR was approved 14 months ago. This PR is unmerged.

Has this project been abandoned?

**Comment by neillom** [comment]
As this pull request is in conflict I have committed and pushed the same change in request #61 to expedite the inclusion. This request can now be closed with the merge or 61

**Comment by alexmac05** [comment]
https://github.com/hellosign/hellosign-python-sdk/pull/61 waiting for this merge before we can test

**Comment by jtreminio-dropbox** [comment]
Please use the new OpenAPI SDK: https://pypi.org/project/dropbox-sign/

**Pull request closed without merging**
